/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-5BiL3ePC4qlmhtIuEVUB7-0YdW8gp7-RScVmyq94NuGVUlQJ-dTm9b8EI19ApECcAV-WKbmEMGiKa4wAqFb980IvewkTQISWNHHzwPgDdomdeOFqxpvxCAtf",
  "tt": "tt-1-Gy5jcO5D8SzOg6hnEt-OPR9v9abcYh4FL8ALOIe7HwI=",
  "version": "2020-11-20"
}

export default ebconfig;