/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-HYtbY0Y5VPYF9ssjRz1jLaCKQExJiZFiVlwbS-fOndA4M-b3i9nxpXQ6bc96FJnLvpTe7mVAH7OQtzy7drjQdMHIfXhkGBFXW9TPzEMAji8oN81dwkNPo9bM",
  "tt": "tt-1-0vbMJ-jbbbemil6t-10NjE66Yn4yz4UuSMc37ZwEidM=",
  "version": "2020-11-20"
}

export default ebconfig;